{% set name = "pyrush" %}
{% set version = "1.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyRuSH-{{ version }}.tar.gz
  sha256: 73f53cb1bd651d6ce68521ec28a571ad426b6e838e75daf4c9e25fd868293f60

build:
  # cymem, spacy, preshed aren't available for s390x
  skip: true  # [s390x]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - cymem 2.0.6
    - cython 0.29.32
    - numpy {{ numpy }}
    - pip
    - preshed 3.0.6
    - pyfastner 1.0.8
    - quicksectx 0.3.5
    - setuptools
    - spacy 3.3.1
    - wheel
  run:
    - python
    - cython >=0.25,<3.0
    - pyfastner >=1.0.8
    - quicksectx >=0.3.5
    - spacy >=3.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - PyRuSH
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jianlins/PyRuSH
  dev_url: https://github.com/jianlins/PyRuSH
  doc_url: https://github.com/jianlins/PyRuSH
  summary: A fast implementation of RuSH (Rule-based sentence Segmenter using Hashing).
  description: |
    A fast implementation of RuSH (Rule-based sentence Segmenter using Hashing).
  license: MIT
  license_family: MIT
  # The source code for this package doesn't have license file.
  license_url: https://github.com/jianlins/PyRuSH/blob/master/LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
  skip-lints:
    - cython_must_be_in_host
    - python_build_tool_in_run
